# Generated by Django 4.0.2 on 2022-02-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
