# Generated by Django 4.0.2 on 2022-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_rename_author_id_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
    ]
